insert into objects (`UID`, `ParentProjectId`, `Name`, `Status`, `PercentComplete`,
                   `SystemStartDate`, `SystemEndDate`, `PlannedStartDate`,
                     `PlannedEndDate`, `ActualStartDate`, `ActualEndDate`,
                     `OwnerId`, `ResponsibleId`)
values ('$UID',
        '$ParentProjectId',
        '$Name',
        '$Status',
        '$PercentComplete',
        '$SystemStartDate',
        '$SystemEndDate',
        '$PlannedStartDate',
        '$PlannedEndDate',
        '$ActualStartDate',
        '$ActualEndDate',
        '$OwnerId',
        '$ResponsibleId');